java_test(
    name = "CommandTest",
    srcs = ["CommandTest.java"],
    deps = [
        "//com.google.devtools.bazel.e4b/src/com/google/devtools/bazel/e4b/command",
        "@com_google_truth//jar",
        "@org_hamcrest_core//jar",
        "@org_junit//jar",
    ],
)
