java_library(
    name = "command",
    srcs = glob(["*.java"]),
    visibility = [
        "//com.google.devtools.bazel.e4b:__pkg__",
        "//javatests/com/google/devtools/bazel/e4b/command:__pkg__",
    ],
    deps = [
        "@com_google_guava//jar",
        "@org_json//jar",
    ],
)
