java_library(
    name = "projectviews",
    srcs = glob(["*.java"]),
    visibility = [
        "//:__pkg__",
        "//javatests/com/google/devtools/bazel/e4b/projectviews:__pkg__",
    ],
    deps = [
        "@com_google_guava//jar",
    ],
)
