# This is a workspace file for creating a local repository added with --override_repository when
# using the aspect so we can load the e4b_aspect.bzl Skylark aspect extension when calling build
# from Eclipse.