load("//tools/build_defs:eclipse.bzl", "eclipse_p2updatesite")

eclipse_p2updatesite(
    name = "p2updatesite",
    description = "Eclipse plugin for Bazel",
    eclipse_features = ["//com.google.devtools.bazel.e4b.feature"],
    label = "Eclipse 4 Bazel",
    url = "https://bazelbuild.github.io/e4b",
)
