java_test(
    name = "ProjectViewTest",
    srcs = ["ProjectViewTest.java"],
    resources = ["bazel.projectview"],
    deps = [
        "//java/com/google/devtools/bazel/e4b/projectviews",
        "@com_google_truth//jar",
        "@org_hamcrest_core//jar",
        "@org_junit//jar",
    ],
)
