java_library(
    name = "command",
    srcs = glob(["*.java"]),
    visibility = [
        "//:__pkg__",
        "//javatests/com/google/devtools/bazel/e4b:__subpackages__",
    ],
    deps = [
        "@com_google_guava//jar",
        "@org_json//jar",
    ],
)
