package(default_visibility = ["//visibility:public"])

py_binary(
    name = "feature_builder",
    srcs = ["feature_builder.py"],
    deps = ["@com_google_python_gflags//:gflags"],
)

py_binary(
    name = "site_builder",
    srcs = ["site_builder.py"],
    deps = ["@com_google_python_gflags//:gflags"],
)
